import { FumbleDefinition } from './types';

export const campaignSettings = [
  "High Fantasy", "Dark Fantasy", "Cyberpunk", "Sci-Fi / Space Opera", 
  "Gothic Horror", "Post-Apocalyptic", "Steampunk", 
  "Modern / Urban Fantasy", "Western", "Pirate / Nautical"
];

export const gameSystems = [
  { id: 'generic', label: 'System Agnostic / Narrative', title: "That's a 1" },
  { id: 'dnd5e', label: 'D&D 5e', title: "That's a Nat 1" },
  { id: 'pf2e', label: 'Pathfinder 2e', title: "That's a Crit Fail" },
  { id: 'coc', label: 'Call of Cthulhu / BRP', title: "That's a 100" },
];

export const fumbles: FumbleDefinition[] = [
    // =================================================================
    //                              MELEE
    // =================================================================
    
    // --- Extreme Silly (0-15) ---
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you swing so hard you spin 360 degrees and hit the enemy with your butt. It is ineffective." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "Take 1 non-lethal damage to your ego.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "your pants fall down around your ankles. You cannot move until you pull them up." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "You are Restrained by your trousers.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you accidentally hug the enemy instead of attacking them. It gets awkward." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "Make a Persuasion check instead of an attack.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "your weapon flies out of your hand and lands in your own scabbard perfectly. You dealt no damage." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you slip on a banana peel (or setting equivalent) that wasn't there a moment ago." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you sneeze so hard you headbutt the floor." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you start crying uncontrollably for no reason." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "your weapon dissolves into a bouquet of flowers (illusion). It returns to normal next turn." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you attack an imaginary friend that only you can see." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "your battle cry cracks and comes out as a high-pitched squeak." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you tickle the enemy instead of harming them." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "your weapon turns into a rubber chicken for 1 round." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you trip and roll between the enemy's legs, ending up behind them looking confused." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "you aggressively high-five the enemy's face. It stings a little." },
    { type: 'Melee', minTone: 0, maxTone: 15, text: "your swing carries you into a pirouette. Make a Performance check." },
    
    // --- Silly / Clumsy (16-35) ---
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you swing so hard you spin like a top. You are dizzy." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "Disadvantage next turn due to dizziness.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "your weapon gets stuck in a nearby wooden object. It takes effort to yank it out." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "your weapon gets stuck. Requires an Action to remove.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you announce your attack loudly, allowing the enemy to simply step aside." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you accidentally hit yourself with the pommel. Minor bruise." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "Take 1 bludgeoning damage.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "your belt buckle fails. You must use one hand to hold up your gear." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you trip over your own feet." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "your weapon catches on your own clothing, ripping a hole." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you startle yourself with your own battle cry." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you pull a hamstring trying a fancy move. Speed reduced." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "Speed is halved.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "your sweaty palms cause the weapon to fly out of your hand." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you get distracted by a shiny object." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you bite your tongue. Speaking is painful." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you lunge too far and roll into a ball." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "your helmet slides over your eyes. You are blind momentarily." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you get the hiccups immediately." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "Disadvantage on Concentration.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you high-five the enemy's shield. Your hand hurts." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you accidentally sheath your weapon." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you step on your own cloak/coat and stumble." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "your weapon vibrates violently on impact, numbing your arm." },
    { type: 'Melee', minTone: 16, maxTone: 35, text: "you hit the floor, jarring your shoulder." },

    // --- Balanced / Unfortunate (36-65) ---
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you overextend and lose your footing. You fall." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "You are knocked Prone.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "your guard drops. Defending yourself is harder." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "Next attack against you has Advantage.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "your weapon jars your wrist painfully. You drop the weapon." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you stumble into the enemy's space. You are vulnerable." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "You provoke an Opportunity Attack.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "your weapon gets tangled in your own armor. You struggle to free it." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "Lose your Reaction this round.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you hit the enemy's armor at a bad angle. Your hand is numb." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "-2 to hit on your next attack.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "the enemy catches your blade. They attempt to disarm you." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you telegraph the attack. The enemy predicts your moves." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "sand/dust gets in your eyes. Vision impaired." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "Blinded until you clear your eyes (Action).", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you strike a wall hard. Weapon vibrates painfully." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you slip in mud/blood. Save or fall." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you leave yourself wide open. Enemy grabs you." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you lose your grip. Weapon slides 5ft away." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you clash weapons, but yours is pushed aside." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "your foot gets stuck in loose terrain. Cannot move." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "Speed is 0 until start of next turn.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you hesitate. Initiative suffers next round." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you accidentally clip your own shield. Defense falters." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you strike with the flat of the blade. No damage." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you strain a calf muscle. Running is painful." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you collide with an adjacent ally." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "your weapon hilt is slick with sweat. Disadvantage next attack." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you accidentally kick a rock. Foot hurts. -5 movement." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "a bug flies in your eye. Distracted." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "your attack leaves you over-balanced. You cannot Dodge." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you hit the enemy's weapon, damaging the edge of yours." },
    { type: 'Melee', minTone: 36, maxTone: 65, text: "you wrench your back. Disadvantage on Str checks." },

    // --- Gritty / Painful (66-85) ---
    { type: 'Melee', minTone: 66, maxTone: 85, text: "you strike a hard surface. Your weapon chips." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "you tear a muscle in the swing. Painful." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Take 1d6 damage. Speed halved.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Friendly Fire! You miss and hit an ally." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Roll damage against the nearest ally.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "the enemy parries with brutal force, dislocating your shoulder." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Disadvantage on attacks until healed.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "you fall directly onto your own weapon." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Roll weapon damage against yourself.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "the enemy uses your momentum to throw you." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Take 1d6 bludgeoning and land Prone.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Bone fracture. You break a finger hitting their shield." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "blood gets in your eyes. Blinded in one eye." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "the enemy twists your arm. You drop the weapon." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "catastrophic overswing. You are reeling." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Stunned until start of next turn.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "you slash your own leg." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Reduce speed by 10ft. Take 1d8 slashing.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "the enemy catches your weapon and snaps it. Weapon broken." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "concussion. You are dazed." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "Confusion spell effect for 1 minute.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "your armor strap breaks. AC reduced." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "you are winded. Cannot act effectively." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "internal bleeding. You take continuous damage." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "your weapon jams in your armor. Restrained." },
    { type: 'Melee', minTone: 66, maxTone: 85, text: "you hit your own shin with the crossguard/haft. Limp." },

    // --- Extreme Lethal (86-100) ---
    { type: 'Melee', minTone: 86, maxTone: 100, text: "you sever your own finger/thumb in the mechanism or guard." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "Lose usage of hand permanently. Take 2d6 damage.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "you trip and impale yourself on your own weapon through a vital organ." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "Drop to 0 HP and begin dying.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "Gain Dying 2.", systems: ['pf2e'] },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "the enemy ripostes perfectly, piercing your heart/throat." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "Critical Hit against you. Max damage.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "your weapon shatters into shrapnel, blinding you permanently." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "you hit a structural support. The ceiling collapses on the party." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "Everyone takes 4d6 bludgeoning. Dex save for half.", systems: ['dnd5e'] },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "you accidentally decapitate the nearest ally. Oops." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "you tear your rotator cuff completely. Arm useless until Regenerate spell." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "Massive hemorrhage. You will die in 1d4 rounds without magical healing." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "you stumble into the enemy's blade. Auto-crit against self." },
    { type: 'Melee', minTone: 86, maxTone: 100, text: "you slip and shatter your kneecap. Movement permanent 0." },

    // =================================================================
    //                              RANGED
    // =================================================================
    
    // --- Extreme Silly (0-15) ---
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you shoot yourself in the foot. Literally. It tickles." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "your arrow unfurls a small flag that says 'BANG!'." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you accidentally throw the bow at the enemy and keep the arrow." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "Make an improvised thrown weapon attack.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "your pants fall down while aiming. You miss." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you sneeze and shoot the hat off your ally's head." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "the projectile does a U-turn and lands in your pocket." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you get tangled in your weapon like a pretzel. Restrained." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you forgot to let go of the arrow. You slap yourself in the face." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "a bird intercepts your projectile and explodes in a puff of feathers." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you load the wrong end of the arrow/bolt." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "your weapon emits a loud squeaky toy noise on release." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you fire, but the projectile just flops out of the barrel/string." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you hiccup and shoot the dirt 2 feet in front of you." },
    { type: 'Ranged', minTone: 0, maxTone: 15, text: "you accidentally fire two arrows/bullets at once, and they collide mid-air." },

    // --- Silly / Clumsy (16-35) ---
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "the projectile falls out of your weapon and lands on your toe." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "Take 1 damage.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you sneeze right as you release. The shot flies straight up." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you forgot to load the weapon. Loud 'click' noise." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "the mechanism slaps your cheek. Face is red and stinging." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "Disadvantage on Charisma.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you shoot a nearby innocent object (vase, chicken)." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "your ammo bag spills. Marbles/arrows everywhere." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you get your finger stuck in the trigger guard." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you fire but forgot to let go. You punch the air." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you accidentally shoot the ceiling. Debris falls." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you mistake your lunch for a projectile." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "weapon makes a comical whistle sound." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you trip over your quiver/ammo box." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "a gust of wind blows the projectile back at you (harmlessly)." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you close the wrong eye while aiming." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "your weapon snags on a nearby branch/furniture." },
    { type: 'Ranged', minTone: 16, maxTone: 35, text: "you lose count of your ammo and fire on empty." },

    // --- Balanced / Unfortunate (36-65) ---
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "the string snaps or gun jams. Requires repair." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "Requires an Action to fix.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "you fumble the reload. Action wasted." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "you lose your footing while aiming. Shot goes wide and you fall." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "Fall Prone.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "your ammo pouch spills. Must gather shots." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "you lose sight of the target. Cannot attack them." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "you clip an ally. They are distracted." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "Ally -2 to next roll.", systems: ['dnd5e', 'pf2e'] },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "shot goes wide and hits a structural support." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "bad fletching/powder. Shot veers wildly." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "Reroll attack against random target.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "eyes water. Aiming is hard." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "Disadvantage on ranged next turn.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "sun glare blinds you." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "you take too long to aim. Initiative drops." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "recoil knocks you off balance." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "bow limb cracks. -2 damage until fixed." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "you drop your ammo in the mud. It's dirty/wet." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "cramp in arm. Cannot attack next round." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "your sleeve gets caught in the string/mechanism." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "you accidentally knock your own ammo pouch upside down." },
    { type: 'Ranged', minTone: 36, maxTone: 65, text: "smoke/dust from the shot obscures your vision." },

    // --- Gritty / Painful (66-85) ---
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "Ricochet! Shot hits you." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "Roll damage against yourself.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "Structural failure. Weapon explodes in hands." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "Take 1d8 fire/piercing.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "you hit a random ally. You injure them." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "recoil snaps a wrist bone. Cannot use 2H weapons." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "Scope bite / String slap to eye. One eye blind." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "shot pierces volatile container. Explosion." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "you hit a bystander." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "critical malfunction. Weapon broken." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "projectile shatters. Shrapnel blinds allies." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "Nearby allies Blinded.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "weapon backfires. Burned and deafened." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "you shoot your own foot. Cannot walk." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "splinter drives into hand. Disadvantage on Dex checks." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "hot shell casing/string burns neck. Distracted." },
    { type: 'Ranged', minTone: 66, maxTone: 85, text: "weapon flies out of hand from recoil and breaks." },

    // --- Extreme Lethal (86-100) ---
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "your weapon detonates with massive force." },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "Take 4d6 fire. Weapon disintegrated. Hand mangled.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "you shoot your ally in the back of the head." },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "Critical Hit on ally. They are Dying.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "ricochet hits you in the eye. Permanent blindness." },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "stray shot hits the dungeon's support beam. Total collapse imminent." },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "you pierce a container of alchemist's fire on your own belt." },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "You are engulfed in flames. 2d6 fire/turn.", systems: ['dnd5e'] },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "you sever the rope holding the chandelier/trap above you." },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "you accidentally skewer a holy relic. The gods are furious." },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "projectile passes through enemy and hits a magical node. Explosion." },
    { type: 'Ranged', minTone: 86, maxTone: 100, text: "weapon blowback shatters your jaw. Cannot speak." },

    // =================================================================
    //                              SPELL
    // =================================================================
    
    // --- Extreme Silly (0-15) ---
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you accidentally cast the spell on your own pants. They animate and run away." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you summon a confused cow directly above you. Mooo." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "Dex save to avoid cow.", systems: ['dnd5e'] },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "your skin turns polka-dotted and glows in the dark." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you burp a swarm of harmless butterflies." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you turn into a potted plant for 1 round." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "magic backfires and makes you bald instantly." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you summon 1d100 rubber ducks." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "your voice changes to helium-high pitch for 1 hour." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "spell creates a small raincloud that only rains on you." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you swap genders for 1d4 hours." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "all your hair falls out instantly." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you summon a mariachi band that follows you for 10 mins." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "your hands turn into large lobster claws for 1 minute." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you can only speak in rhyme for the next hour." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "the spell casts Confetti Explosion instead." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "you levitate upside down and can't get down." },
    { type: 'Spell', minTone: 0, maxTone: 15, text: "your face rearranges itself (Picasso style) for 1 hour." },

    // --- Silly / Clumsy (16-35) ---
    { type: 'Spell', minTone: 16, maxTone: 35, text: "bouquet of wilted flowers shoots from focus." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "verbal components spoken backward. Turn blue." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "raincloud forms over your head." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "cast Grease on self." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "voice cracks. Spell becomes loud burp." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "summon confused chicken." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "hair grows several feet." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "swap positions with target. Spell fails." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "illusionary butterflies erupt from mouth." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "focus turns into rubber duck." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "sneeze ectoplasm." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "clothes change to neon pink." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "spectral band plays circus music." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "shrink by 6 inches." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "hands become slippery with oil." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "cast Light on your own nose." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "gravity reverses for you only." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "you float 2 inches off the ground, unable to move." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "you become magnetic. Metal items stick to you." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "loud elevator music plays from your location." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "you smell strongly of garlic." },
    { type: 'Spell', minTone: 16, maxTone: 35, text: "sparks fly from your ears." },

    // --- Balanced / Unfortunate (36-65) ---
    { type: 'Spell', minTone: 36, maxTone: 65, text: "magic fizzles. Resource lost." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "Lose Spell Slot.", systems: ['dnd5e'] },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "feedback silences you." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "Silenced 1 round.", systems: ['dnd5e'] },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "spell targets random nearby creature." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "blinded by flash." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "focus glows hot. Drop it." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "surge of lethargy. No reactions." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "spell fires late. Misses." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "drain energy from ally." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "recoil knocks you down." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "static shock damage." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "fog cloud on self." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "spell bounces off reflective surface." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "component pouch tears." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "spell works at minimum power." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "forget somatic gesture. Fail." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "magic siphons from boots. Slowed." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "become weak to element used." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "spell targets the nearest corpse." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "you are deafened by thunderclap." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "uncontrollable shaking. Disadvantage on attacks." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "caster glows brightly. Cannot hide." },
    { type: 'Spell', minTone: 36, maxTone: 65, text: "minor magical feedback. 1d4 damage." },

    // --- Gritty / Painful (66-85) ---
    { type: 'Spell', minTone: 66, maxTone: 85, text: "Wild Magic Surge!" },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "Roll Wild Magic.", systems: ['dnd5e'] },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "Psychic Backlash. Mind consumed." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "Take 1d6 per spell level.", systems: ['dnd5e'] },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "Weave tears. Hostile entity summoned." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "Necrotic rot on arm. Max HP reduced." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "spell implodes. AOE damage." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "open rift to hostile plane." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "Lose 1d6 Sanity.", systems: ['coc'] },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "spell targets YOU for full damage." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "mind cracks. Madness." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "focus shatters. Damage taken." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "pulled into Astral plane for 1 min." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "age 1d10 years." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "lose memory of 24 hours." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "spell feeds on life force. Unconscious." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "hands catch fire. Burn." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "spell becomes permanent anti-magic field on self." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "you forget your highest level spell slot." },
    { type: 'Spell', minTone: 66, maxTone: 85, text: "blood pours from your eyes. Blinded 1 min." },

    // --- Extreme Lethal (86-100) ---
    { type: 'Spell', minTone: 86, maxTone: 100, text: "your soul is torn from your body." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "Instant Death.", systems: ['dnd5e'] },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "you summon a Greater Demon who is unbound and angry." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "the spell creates a black hole. Everything in 30ft sucked in and crushed." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "you turn yourself into stone permanently." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "Petrified condition.", systems: ['dnd5e'] },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "you explode with magical force." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "Cast Fireball centered on self.", systems: ['dnd5e'] },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "magic erasure. You lose ability to cast spells permanently." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "portal to the Far Realm opens. Look upon the infinite." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "Lose 1d100 Sanity.", systems: ['coc'] },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "you fuse with the nearest solid object." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "spell causes a magical plague outbreak." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "you are erased from history. No one remembers you." },
    { type: 'Spell', minTone: 86, maxTone: 100, text: "the spell consumes your physical form, leaving only a shadow." },

    // =================================================================
    //                              SOCIAL
    // =================================================================
    
    // --- Extreme Silly (0-15) ---
    { type: 'Social', minTone: 0, maxTone: 15, text: "you accidentally propose marriage." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you burp the national anthem." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "your pants fall down. Again." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you faint from nervousness." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you confess your undying love for a nearby lamp." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you forget your own name." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you start mimicking the NPC perfectly without realizing it." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you laugh so hard you wet yourself." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you get the hiccups in the middle of a serious sentence." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you sneeze on the NPC." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you accidentally call the NPC 'Mommy' or 'Daddy'." },
    { type: 'Social', minTone: 0, maxTone: 15, text: "you perform a rude gesture thinking it's a greeting." },
    
    // --- Silly / Clumsy (16-35) ---
    { type: 'Social', minTone: 16, maxTone: 35, text: "spit on person." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "use fancy word incorrectly (manure)." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "call them Mom/Dad." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "food stuck in teeth." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "accidentally kiss nose." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "stomach growls." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "trip and fall." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "sneeze and headbutt." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "inappropriate laugh." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "wardrobe malfunction." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "bad wink." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "handshake fail." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "insult pet." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "forget language momentarily." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "hug them uncomfortably long." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "voice squeaks." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "accidentally imply you are a spy." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "drool slightly." },
    { type: 'Social', minTone: 16, maxTone: 35, text: "call them by their rival's name." },

    // --- Balanced / Unfortunate (36-65) ---
    { type: 'Social', minTone: 36, maxTone: 65, text: "offend ancestors." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "reveal secret." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "misinterpreted sarcasm." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "stutter/stumble." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "confuse NPC with someone else." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "bore them." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "insult fashion." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "look shady." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "get name wrong." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "zone out." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "step on toes." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "smell bad." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "accidentally imply bribe." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "spill drink on them." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "appear cowardly." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "insult their cooking/hospitality." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "talk over them repeatedly." },
    { type: 'Social', minTone: 36, maxTone: 65, text: "accidentally reveal party location." },

    // --- Gritty / Painful (66-85) ---
    { type: 'Social', minTone: 66, maxTone: 85, text: "perceived threat. Weapons drawn." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "duel demanded." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "trigger sleeper agent. Attack." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "accidental blood oath." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "recognized from Wanted poster." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "cause heart attack." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "reveal info to spy." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "confess to crime." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "make shapeshifter hungry." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "bribe insult." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "insult their god." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "accused of witchcraft." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "insult their spouse/child." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "guards called immediately." },
    { type: 'Social', minTone: 66, maxTone: 85, text: "blackmailed." },

    // --- Extreme Lethal (86-100) ---
    { type: 'Social', minTone: 86, maxTone: 100, text: "you insult the monarch/god directly. You are marked for immediate execution." },
    { type: 'Social', minTone: 86, maxTone: 100, text: "your words incite a riot. The mob turns on you." },
    { type: 'Social', minTone: 86, maxTone: 100, text: "you accidentally utter a Power Word Kill on yourself." },
    { type: 'Social', minTone: 86, maxTone: 100, text: "the NPC reveals themselves as a high-level Dragon/Demon and eats you." },
    { type: 'Social', minTone: 86, maxTone: 100, text: "you trigger a magical geas that liquefies your bones." },
    { type: 'Social', minTone: 86, maxTone: 100, text: "you start a war." },
    { type: 'Social', minTone: 86, maxTone: 100, text: "you pledge your firstborn/soul accidentally." },
    { type: 'Social', minTone: 86, maxTone: 100, text: "you are exiled from the plane of existence." },
    
    // =================================================================
    //                              SKILL
    // =================================================================
    
     // --- Extreme Silly (0-15) ---
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you get your head stuck in the bucket you were investigating." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you trip and roll down the entire flight of stairs like a cartoon character." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you mistake a mimic for a chair and sit on it." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you use the wrong tool and dismantle your own pants." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you fart incredibly loudly while hiding." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you get your hand stuck in the jar." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you lick the unknown substance. It tastes like purple." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you accidentally lock yourself in the chest." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you forget how to use doors." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you are distracted by your own reflection." },
    { type: 'Skill', minTone: 0, maxTone: 15, text: "you fall asleep on the job." },

    // --- Silly / Clumsy (16-35) ---
    { type: 'Skill', minTone: 16, maxTone: 35, text: "step on squeaky toy." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "stuck in window." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "vault fence faceplant." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "loud sneeze." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "pants rip loudly." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "lock self IN room." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "distracted by animal." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "drop tools. Loud noise." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "mix potions. Glitter explosion." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "fall asleep." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "signal enemy." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "glue hands together." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "knock over shelf." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "read map upside down." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "tie knots in own shoelaces." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "lose compass." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "drop torch in puddle." },
    { type: 'Skill', minTone: 16, maxTone: 35, text: "accidentally hum a tune while sneaking." },

    // --- Balanced / Unfortunate (36-65) ---
    { type: 'Skill', minTone: 36, maxTone: 65, text: "lockpick snaps. Jammed." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "trip noisemaker trap." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "fall climbing." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "knock over vase." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "misread runes. False info." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "break item." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "spotted by civilian." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "slide down roof." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "drop artifact." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "leave footprints." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "torch goes out." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "inhale dust. Cough." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "sprain ankle jumping." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "rope unravels." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "drop potion." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "alert guard dog." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "trigger alarm spell." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "get stuck in tight crawlspace." },
    { type: 'Skill', minTone: 36, maxTone: 65, text: "ruin delicate machinery." },

    // --- Gritty / Painful (66-85) ---
    { type: 'Skill', minTone: 66, maxTone: 85, text: "trigger poison needle." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "fall from height. Dying." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "caught by elite guard." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "device explodes. Blinded." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "destroy quest item." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "ceiling collapse." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "alert entire dungeon." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "disturb nesting monster." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "crush hand." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "fall into acid/lava." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "find forbidden knowledge." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "breathe in toxic spores." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "get hopelessly lost." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "break limb in fall." },
    { type: 'Skill', minTone: 66, maxTone: 85, text: "touch cursed object." },

    // --- Extreme Lethal (86-100) ---
    { type: 'Skill', minTone: 86, maxTone: 100, text: "you touch the artifact and are disintegrated instantly." },
    { type: 'Skill', minTone: 86, maxTone: 100, text: "Sphere of Annihilation." },
    { type: 'Skill', minTone: 86, maxTone: 100, text: "you fall into the endless void." },
    { type: 'Skill', minTone: 86, maxTone: 100, text: "you accidentally summon an army of undead upon the city." },
    { type: 'Skill', minTone: 86, maxTone: 100, text: "your mind is completely wiped blank." },
    { type: 'Skill', minTone: 86, maxTone: 100, text: "you solve the puzzle, but it summons Cthulhu." },
    { type: 'Skill', minTone: 86, maxTone: 100, text: "you trigger the self-destruct sequence. 10 seconds remaining." },
    { type: 'Skill', minTone: 86, maxTone: 100, text: "you release the Ancient Evil." },
    { type: 'Skill', minTone: 86, maxTone: 100, text: "you become the trap." },
];